// <auto-generated />
using System;
using DooProject.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DooProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230207081230_SQLiteMigration_1")]
    partial class SQLiteMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("DooProject.Models.ProductLookUp", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.ToTable("ProductLookUps");
                });

            modelBuilder.Entity("DooProject.Models.ProductTransection", b =>
                {
                    b.Property<int>("TransectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransectionAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransectionID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductTransections");
                });

            modelBuilder.Entity("DooProject.Models.ProductTransection", b =>
                {
                    b.HasOne("DooProject.Models.ProductLookUp", "ProductLookUp")
                        .WithMany("ProductTransections")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductLookUp");
                });

            modelBuilder.Entity("DooProject.Models.ProductLookUp", b =>
                {
                    b.Navigation("ProductTransections");
                });
#pragma warning restore 612, 618
        }
    }
}
